name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compile report
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: report
          root_file: main.tex
      
      - name: Cache scala tools
        uses: coursier/cache-action@v6
      
      - name: Install scala tools
        uses: coursier/setup-action@v1
        with:
          apps: sbtn scalafmt
      
      - name: Check project formatting
        working-directory: lang/
        run: scalafmt --test
          
      
